-- 코드를 입력하세요

SELECT D.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY, C.TOTAL_SALES
FROM 
(
SELECT A.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, SUM(B.PRICE * A.SALES) AS TOTAL_SALES
FROM
    (SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
    GROUP BY BOOK_ID) A
JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY, B.AUTHOR_ID
) C JOIN AUTHOR D ON C.AUTHOR_ID = D.AUTHOR_ID
ORDER BY D.AUTHOR_ID, C.CATEGORY DESC