-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH, 
    COUNT(DISTINCT A.USER_ID) PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT A.USER_ID)/(SELECT COUNT(*)
                         FROM USER_INFO
                         WHERE YEAR(JOINED) = '2021'),1) PUCHASED_RATIO
FROM ONLINE_SALE A JOIN USER_INFO B ON A.USER_ID=B.USER_ID
WHERE YEAR(JOINED) = '2021'
GROUP BY 1, 2
ORDER BY 1, 2