-- 코드를 입력하세요
SELECT a.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS T FROM FIRST_HALF
      GROUP BY FLAVOR) a, (SELECT FLAVOR, SUM(TOTAL_ORDER) AS T FROM JULY
      GROUP BY FLAVOR) b
WHERE a.FLAVOR = b.FLAVOR
ORDER BY a.T + b.T DESC
LIMIT 3