-- 코드를 작성해주세요
-- FISH_TYPE별 가장 큰 LENTH 구해서 걔랑 FISH_NAME_INFO랑 조인하면 안되나??

SELECT 
    A.ID, B.FISH_NAME, A.LENGTH
FROM
    FISH_INFO A
JOIN
    FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE
    (A.FISH_TYPE, A.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE)
ORDER BY A.ID;